#!/bin/sh
if [ -e "/odm/default.prop" ]
then
    break
else
    cp /vendor/etc/default.prop.template /odm/default.prop
fi

if [ -e "/odm/afrd.ini" ]
then
    break
else
    cp /vendor/etc/afrd.ini.template /odm/afrd.ini
fi

if [ -e "/odm/usb_modeswitch.conf" ]
then
    break
else
    cp /vendor/etc/usb_modeswitch.conf.template /odm/usb_modeswitch.conf
fi
